name: Pull Request

on: [pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"

      - name: Run Tests
        run: go test -race -coverpkg=./... -coverprofile=coverage.out -covermode=atomic

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
